#!/bin/sh
SAVE_DIR=~/bks/pomodoros_freetime
case $1 in
	add)	start=$2
		start_secs=$(date -d $start +'%s')
		end=$3
		end_secs=$(date -d $end +'%s')
		duration="$(( ($end_secs - $start_secs)/60 ))"
		echo "Pomodoro 1: $start to $end ($duration) $(date '+%Y%b%d')" | tee -ai $SAVE_DIR;;
	*)	muccadoro ${1:-25} 'f' | tee -ai "$SAVE_DIR"
esac
pkill -RTMIN+3 dwmblocks
